---
output:
  html_document
---

Here is the Table of Content (toc):

* Data Stories
    + [Toxic Beauty](work_toxic_beauty.html)
    + [Plastic Fashion](work_plastic_fashion.html)
    + [Fabric of Community](work_fabric_of_community.html)
* Five Minute Conversations
    + [Todd Sieling](work_todd_sieling.html)
    
<div id="work">
</div>

And these are all the separte html pages for each work:  
[work_toxic_beauty.html](work_toxic_beauty.html)  
[work_plastic_fashion.html](work_plastic_fashion.html)  
[work_fabric_of_community.html](work_fabric_of_community.html)  
[work_todd_sieling.html](work_todd_sieling.html)


I understand we have two ways to put all this together:

1. every work page contains the toc.
2. only work.html (this page) contains the toc. When a link is clicked the 
  content of the relevant work will be loaded in this page. For this to work, 
  I imagine we need a placeholder (a div?) for work content. 
  
####__TODO for Arian:__

Decide which approach described above is better and let Maryam know. 
(I personally think #2 makes more sense, but you know better and I like to hear 
your opinion. I have included an emoty `<div id="work"></div>` in this html for now.)
